"use client";

import styled from "styled-components";

const Container = styled.div`
  max-width: 600px;
  margin: 0 auto;
  padding: 60px 24px;
`;

const BackLink = styled.a`
  color: rgba(255, 255, 255, 0.35);
  font-size: 14px;
  margin-bottom: 32px;
  display: inline-block;
  transition: color 0.2s;

  &:hover {
    color: rgba(255, 255, 255, 0.6);
  }
`;

const Title = styled.h1`
  font-family: var(--font-instrument-serif), serif;
  font-size: 32px;
  font-weight: 400;
  margin-bottom: 32px;
`;

const Section = styled.h2`
  font-family: var(--font-instrument-serif), serif;
  font-size: 20px;
  font-weight: 400;
  color: rgba(255, 255, 255, 0.8);
  margin-top: 28px;
  margin-bottom: 10px;
`;

const Text = styled.p`
  font-size: 15px;
  line-height: 1.7;
  color: rgba(255, 255, 255, 0.6);
  margin-bottom: 12px;
`;

export default function TermsPage() {
  return (
    <Container>
      <BackLink href="/">&larr; Back</BackLink>
      <Title>Terms of Service</Title>
      <Text>Last updated: April 2026</Text>

      <Section>Acceptance of terms</Section>
      <Text>
        By accessing or using LoveReply (&quot;the Service&quot;), you agree to be bound
        by these Terms of Service. If you do not agree to these terms, do not
        use the Service.
      </Text>

      <Section>Description of the Service</Section>
      <Text>
        LoveReply provides AI-generated communication suggestions for personal
        relationships. The Service uses your own Anthropic API key to generate
        responses. LoveReply acts solely as an interface between you and
        Anthropic&apos;s API.
      </Text>

      <Section>No professional advice</Section>
      <Text>
        The suggestions provided by LoveReply are generated by artificial
        intelligence and are for informational and entertainment purposes only.
        They do not constitute professional relationship counseling,
        psychological advice, therapeutic guidance, or any other form of
        professional advice. You should not rely on the Service as a substitute
        for professional help.
      </Text>

      <Section>Your API key</Section>
      <Text>
        You are solely responsible for your Anthropic API key, including any
        costs incurred through its use. By providing your API key, you confirm
        that you have the right to use it and that its use complies with
        Anthropic&apos;s terms of service. If you share a link containing your API
        key with another person, you do so at your own risk and are responsible
        for any usage that results.
      </Text>

      <Section>User responsibility</Section>
      <Text>
        You are solely responsible for how you use the suggested replies and any
        consequences that result from sending them. The Service provides
        suggestions — the decision to use them is yours alone.
      </Text>

      <Section>Disclaimer of warranties</Section>
      <Text>
        The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of
        any kind, whether express, implied, or statutory. We disclaim all
        warranties, including but not limited to implied warranties of
        merchantability, fitness for a particular purpose, accuracy,
        completeness, and non-infringement. We do not warrant that the Service
        will be uninterrupted, error-free, or secure.
      </Text>

      <Section>Limitation of liability</Section>
      <Text>
        To the maximum extent permitted by applicable law, LoveReply and its
        operators, developers, and affiliates shall not be liable for any
        indirect, incidental, special, consequential, or punitive damages, or
        any loss of profits, data, relationships, goodwill, or other intangible
        losses, resulting from your use of or inability to use the Service,
        regardless of the theory of liability.
      </Text>
      <Text>
        In no event shall our total liability exceed the amount you have paid us
        in the twelve months preceding the claim, which in all cases is zero as
        the Service is provided free of charge.
      </Text>

      <Section>Indemnification</Section>
      <Text>
        You agree to indemnify and hold harmless LoveReply and its operators
        from any claims, damages, losses, or expenses arising from your use of
        the Service, your violation of these terms, or your violation of any
        third-party rights.
      </Text>

      <Section>Third-party services</Section>
      <Text>
        The Service relies on Anthropic&apos;s API, which is subject to its own
        terms of service and privacy policy. We are not responsible for
        Anthropic&apos;s services, availability, or data handling practices.
      </Text>

      <Section>Modifications</Section>
      <Text>
        We reserve the right to modify, suspend, or discontinue the Service at
        any time without notice. We may update these terms at any time. Continued
        use of the Service after changes constitutes acceptance of the updated
        terms.
      </Text>

      <Section>Governing law</Section>
      <Text>
        These terms shall be governed by and construed in accordance with
        applicable law, without regard to conflict of law principles.
      </Text>

      <Section>Contact</Section>
      <Text>
        If you have questions about these terms, please contact us at
        legal@lovereply.ai.
      </Text>
    </Container>
  );
}
